# common top-level Makefile
#
include ../tcamake/projectdefs


all: libproject


.PHONY: libproject
libproject:
	( cd libproject; make all )
	@echo

clean:
	( cd libproject; make clean )
	@echo

distclean:
	( cd libproject; make distclean )
	@echo

install:
	( cd libproject; make install )
	@echo

