#/etc/skel/.bashrc
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi

CURDIR=.
if [ -z "$RC_TNMS_BASHRC" ]; then
    if [ -e ~/tnms/etc/tnmsrc ]; then
        source ~/tnms/etc/tnmsrc
    elif [ -e $CURDIR/tnmsrc ]; then 
        source $CURDIR/tnmsrc
    fi
fi

export PS1="\h{\u}$ "

# tnms
export TNMS_ENV="dev"
export TNMS_HOST=`hostname`
export TNMS_DEBUG="true"

if [ -z "$TNMS_PREFIX" ]; then
    export TNMS_PREFIX="$TNMS_HOME"
fi


