#/etc/skel/.bashrc
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi

CURDIR=.
if [ -z "$RC_TCANMS_BASHRC" ]; then
    if [ -e ~/tcanms/etc/tcanmsrc ]; then
        source ~/tcanms/etc/tcanmsrc
    elif [ -e $CURDIR/tcanmsrc ]; then 
        source $CURDIR/tcanmsrc
    fi
fi

export PS1="\h{\u}$ "

# tcanms
export TCANMS_ENV="dev"
export TCANMS_HOST=`hostname`
export TCANMS_DEBUG="true"

if [ -z "$TCANMS_PREFIX" ]; then
    export TCANMS_PREFIX="$TCANMS_HOME"
fi


