/* wsrxwsrmProxy.h
   Generated by gSOAP 2.8.12 from ../../../../import/wsrm5.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef wsrxwsrmProxy_H
#define wsrxwsrmProxy_H
#include "wsrxH.h"
class wsrm
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'wsrm' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	wsrm()
	{ soap = soap_new(); endpoint = "http://localhost:80"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{"wsrm", "http://schemas.xmlsoap.org/ws/2005/02/rm", "http://docs.oasis-open.org/ws-rx/wsrm/200702", NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~wsrm() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'CreateSequence' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__CreateSequence(struct wsrm__CreateSequenceType *wsrm__CreateSequence, struct wsrm__CreateSequenceResponseType *wsrm__CreateSequenceResponse) { return soap ? soap_call___wsrm__CreateSequence(soap, endpoint, NULL, wsrm__CreateSequence, wsrm__CreateSequenceResponse) : SOAP_EOM; };
	/// Invoke 'CloseSequence' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__CloseSequence(struct wsrm__CloseSequenceType *wsrm__CloseSequence, struct wsrm__CloseSequenceResponseType *wsrm__CloseSequenceResponse) { return soap ? soap_call___wsrm__CloseSequence(soap, endpoint, NULL, wsrm__CloseSequence, wsrm__CloseSequenceResponse) : SOAP_EOM; };
	/// Invoke 'TerminateSequence' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__TerminateSequence(struct wsrm__TerminateSequenceType *wsrm__TerminateSequence, struct wsrm__TerminateSequenceResponseType *wsrm__TerminateSequence_) { return soap ? soap_call___wsrm__TerminateSequence(soap, endpoint, NULL, wsrm__TerminateSequence, wsrm__TerminateSequence_) : SOAP_EOM; };
	/// Invoke 'CreateSequenceResponse' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__CreateSequenceResponse(struct wsrm__CreateSequenceResponseType *wsrm__CreateSequenceResponse) { return soap ? soap_send___wsrm__CreateSequenceResponse(soap, endpoint, NULL, wsrm__CreateSequenceResponse) : SOAP_EOM; };
	/// Invoke 'CloseSequenceResponse' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__CloseSequenceResponse(struct wsrm__CloseSequenceResponseType *wsrm__CloseSequenceResponse) { return soap ? soap_send___wsrm__CloseSequenceResponse(soap, endpoint, NULL, wsrm__CloseSequenceResponse) : SOAP_EOM; };
	/// Invoke 'TerminateSequenceResponse' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__TerminateSequenceResponse(struct wsrm__TerminateSequenceResponseType *wsrm__TerminateSequenceResponse) { return soap ? soap_send___wsrm__TerminateSequenceResponse(soap, endpoint, NULL, wsrm__TerminateSequenceResponse) : SOAP_EOM; };
	/// Invoke 'SequenceAcknowledgement' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__SequenceAcknowledgement() { return soap ? soap_send___wsrm__SequenceAcknowledgement(soap, endpoint, NULL) : SOAP_EOM; };
	/// Invoke 'AckRequested' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__AckRequested() { return soap ? soap_send___wsrm__AckRequested(soap, endpoint, NULL) : SOAP_EOM; };
	/// Invoke 'LastMessage' of service 'wsrm' and return error code (or SOAP_OK)
	virtual int __wsrm__LastMessage() { return soap ? soap_send___wsrm__LastMessage(soap, endpoint, NULL) : SOAP_EOM; };
};
#endif
